'use strict'

/* global describe, it */

// Certificates produced by the BRC-220 reference implementation.
//
// Until this release the library and the reference agreed on the cryptography and on
// nothing else: version, mode, encoding, anchor and the batch path were all written
// differently, and this library rejected every certificate the reference issued with
// "unsupported version: 1.0". Every other test in this directory passed throughout,
// because every other test built its certificates with this library.
//
// The fixture was generated by running the reference's own compiled code — buildProof,
// assembleCertificate, its OP_RETURN encoders, merkleRoot and auditPath — and each
// certificate was accepted by the reference's schema and verifier before it was written.
// Nothing in it was produced by this library; see its _provenance field.
//
// The tests below go both ways. Verifying the reference's certificates shows this library
// reads them; rebuilding each one byte for byte with Certificate.build shows it writes
// the same thing.

require('chai').should()
var fixture = require('../data/notaryhash-reference-certs.json')
var vector = require('../data/brc220-batch-vector.json')
var NH = require('../../lib/notaryhash')
var Certificate = require('../../lib/notaryhash/certificate')
var Merkle = require('../../lib/notaryhash/merkle')
var BN = require('../../lib/crypto/bn')
var Point = require('../../lib/crypto/point')

function opts (header) { return { header: header, requirePow: false } }

// Rebuild a certificate from the proof fields alone, as an issuer using this library would.
function rebuild (ref, merkle) {
  var f = Certificate.toProofInput(ref)
  return Certificate.attachSPV(Certificate.build({
    format: 'reference',
    mode: ref.mode,
    encoding: ref.encoding,
    algorithm: f.algorithm,
    hashAlgorithm: f.hashAlgorithm,
    payloadHash: f.payloadHash,
    publicKey: f.publicKey,
    signature: f.signature,
    createdAtUnix: f.createdAtUnix,
    anchor: ref.anchor,
    merkle: merkle
  }), ref.spv)
}

describe('BRC-220 reference implementation certificates', function () {
  it('come from the reference implementation, not from this library', function () {
    fixture._provenance.should.match(/reference implementation/)
    fixture._provenance.should.match(/verifyCertificateOffline/)
  })

  // A fixture named for a variation it does not actually exercise would pass vacuously.
  describe('each fixture is the variation it is named for', function () {
    var C = fixture.certificates

    it('covers every form the reference accepts that 8.3.0–9.8.0 did not', function () {
      Object.keys(C).should.deep.equal(['fullHex', 'hybridBase64', 'derSignature', 'highS', 'uncompressedKey'])
    })

    it('fullHex is a full-mode, hex certificate', function () {
      C.fullHex.certificate.mode.should.equal('full')
      C.fullHex.certificate.encoding.should.equal('hex')
    })

    it('hybridBase64 is a hybrid-mode, base64 certificate', function () {
      C.hybridBase64.certificate.mode.should.equal('hybrid')
      C.hybridBase64.certificate.encoding.should.equal('base64')
    })

    it('derSignature carries a DER signature', function () {
      var sig = Certificate.toProofInput(C.derSignature.certificate).signature
      sig[0].should.equal(0x30)
      sig.length.should.not.equal(64)
      sig.length.should.equal(C.derSignature.signatureBytes)
    })

    it('highS carries a signature whose s is above n / 2', function () {
      var sig = Certificate.toProofInput(C.highS.certificate).signature
      sig.length.should.equal(64)
      BN.fromBuffer(sig.slice(32)).gt(Point.getN().shrn(1)).should.equal(true)
    })

    it('uncompressedKey carries a 65-byte public key', function () {
      var key = Certificate.toProofInput(C.uncompressedKey.certificate).publicKey
      key.length.should.equal(65)
      key[0].should.equal(0x04)
    })
  })

  describe('direct-anchored', function () {
    Object.keys(fixture.certificates).forEach(function (name) {
      var entry = fixture.certificates[name]

      it(name + ': verifies, all three checks', function () {
        var report = NH.verify(entry.certificate, opts(entry.header))
        report.valid.should.equal(true, JSON.stringify(report.errors))
        report.legacy.should.equal(false)
        report.errors.should.deep.equal([])
      })

      it(name + ': is rebuilt byte for byte by Certificate.build', function () {
        var ours = rebuild(entry.certificate)
        Certificate.canonicalize(ours).should.equal(Certificate.canonicalize(entry.certificate))
      })

      // Guards the test above against a verifier that accepts anything.
      it(name + ': fails with one bit of proofHash changed', function () {
        var p = entry.certificate.proofHash
        var flipped = (parseInt(p[63], 16) ^ 1).toString(16)
        var bad = Object.assign({}, entry.certificate, { proofHash: p.slice(0, 63) + flipped })
        var report = NH.verify(bad, opts(entry.header))
        report.proofIntegrity.should.equal(false)
        report.valid.should.equal(false)
      })
    })

    it('fails against a header for a different block', function () {
      var c = fixture.certificates
      NH.verify(c.fullHex.certificate, opts(c.hybridBase64.header)).valid.should.equal(false)
    })
  })

  describe('batch-anchored', function () {
    var batch = fixture.batch
    var leaves = batch.certificates.map(function (c) { return Buffer.from(c.proofHash, 'hex') })

    batch.certificates.forEach(function (cert, i) {
      it('leaf ' + i + ': verifies, with its inclusion proof', function () {
        var report = NH.verify(cert, opts(batch.header))
        report.valid.should.equal(true, JSON.stringify(report.errors))
        report.batchInclusion.should.equal(true)
      })

      it('leaf ' + i + ': is rebuilt byte for byte by Certificate.build and Merkle.auditPath', function () {
        var ours = rebuild(cert, {
          root: Merkle.root(leaves),
          leafIndex: i,
          leafCount: leaves.length,
          path: Merkle.auditPath(leaves, i)
        })
        Certificate.canonicalize(ours).should.equal(Certificate.canonicalize(cert))
      })
    })

    // The external confirmation of the BRC-220 batch vector: the reference, given the
    // same five proofs, builds the same tree with the same leaf datum.
    it('is the same tree as the BRC-220 batch vector', function () {
      batch.root.should.equal(vector.root)
      batch.certificates.forEach(function (cert, i) {
        cert.proofHash.should.equal(vector.proofs[i].proofHash, 'proofHash ' + i)
        cert.merkle.root.should.equal(vector.root)
        cert.merkle.path.should.deep.equal(vector.proofs[i].path, 'path ' + i)
      })
    })

    it('fails when one leaf presents another leaf\'s path', function () {
      var c = batch.certificates
      var moved = Object.assign({}, c[0], { merkle: Object.assign({}, c[0].merkle, { path: c[1].merkle.path }) })
      var report = NH.verify(moved, opts(batch.header))
      report.batchInclusion.should.equal(false)
      report.valid.should.equal(false)
    })

    it('fails when the leaf count disagrees with the on-chain record', function () {
      var c = batch.certificates[4]
      var recounted = Object.assign({}, c, { merkle: Object.assign({}, c.merkle, { leafCount: 6 }) })
      var report = NH.verify(recounted, opts(batch.header))
      report.anchor.should.equal(false)
      report.valid.should.equal(false)
    })
  })
})
