#!/usr/bin/env node
'use strict'

// Writes version.js from package.json's version, so the browser bundles embed only the
// version STRING — not the whole package.json (its devDependencies/scripts/keywords are
// ~4 KB of dev metadata that used to ride in every bundle via `require('./package.json')`).
// It also decouples package.json edits (e.g. devDep changes) from bundle bytes.
//
// Wired into the `version` npm lifecycle hook alongside sync-cdn-urls; a test
// (test/build/version_sync.js) asserts version.js === package.json.version so it can't drift.

var fs = require('fs')
var path = require('path')
var version = require('../package.json').version
fs.writeFileSync(
  path.join(__dirname, '../version.js'),
  "'use strict'\n// GENERATED by scripts/sync-version.js on `npm version` — do not edit.\nmodule.exports = '" + version + "'\n"
)
